# --- QMIX specific parameters ---

epsilon_start: 1.0
epsilon_finish: 0.05
epsilon_anneal_time: 50000

runner: "episode"

buffer_size: 5000

# update the target network every {} episodes
target_update_interval: 200

# use the Q_Learner to train
agent_output_type: "q"
learner: "q_influence_learner"
double_q: True
mixer: "qmix"
mixing_embed_dim: 32
hypernet_layers: 2
hypernet_embed: 64
e_mode: negative_sample
e_prob: 0.8
regulization: none

name: "qmix_influence"

# --- Agent parameters ---
agent: "rnn_interactive" # Default rnn agent
single_model_name: "./alone_models/"
action_selector: "influence"

# --- pymarl options ---
mac: "basic_mac_influence" # Basic controller
